spring.application.name=blps_kt
spring.profiles.active=${SPRING_PROFILES_ACTIVE:postgres}
server.port=8433
server.forward-headers-strategy=framework
blps.security.accounts-location=${BLPS_SECURITY_ACCOUNTS_LOCATION:${user.dir}/data/security/accounts.xml}
blps.security.accounts-bootstrap-location=${BLPS_SECURITY_ACCOUNTS_BOOTSTRAP_LOCATION:classpath:security/accounts.xml}

yookassa.api-base-url=${YOOKASSA_API_BASE_URL:https://api.yookassa.ru}
yookassa.shop-id=${YOOKASSA_SHOP_ID:1232637}
yookassa.secret-key=${YOOKASSA_SECRET_KEY:test_1ICJ7-3M3zk5gGv7s1tPDCK45DfV0nHlbJ6V1eksem8}
yookassa.return-url=${YOOKASSA_RETURN_URL:http://mil.ru/}
yookassa.webhook-ip-check-enabled=${YOOKASSA_WEBHOOK_IP_CHECK_ENABLED:true}
