package ru.chousik.blps_kt.security

enum class Privilege {
    PRIV_CURRENT_USER_READ,
    PRIV_CHAT_CREATE,
    PRIV_CHAT_READ,
    PRIV_CHAT_LIST,
    PRIV_CHAT_MESSAGE_READ,
    PRIV_CHAT_MESSAGE_WRITE,
    PRIV_EXTRA_SERVICE_CREATE,
    PRIV_EXTRA_SERVICE_READ,
    PRIV_EXTRA_SERVICE_UPDATE,
    PRIV_EXTRA_SERVICE_DELETE,
    PRIV_EXTRA_SERVICE_DECIDE,
    PRIV_EXTRA_SERVICE_PAYMENT_READ
}

